services:
  angular-spring:
    build: ./angular-spring
    ports:
      - "4200:4200"
    volumes:
      - ./angular-spring:/app
      - /app/node_modules
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=library'
      - 'POSTGRES_USER=postgres-user'
      - 'POSTGRES_PASSWORD=admin'
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=rs7951006@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '5050:80'
    depends_on:
      - postgres
volumes:
  postgres-data: